name: Publish
on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & publish to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: dulmandakh/python-poetry:latest